name: KimmeryMartinAuthor
favicon: null
layout_spectrum: 0.655095960944891
typography_spectrum: 0.5088060176931322
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9221383137628436
  lightness: 0.22320172796025872
  saturation: 0.3749444012064487
  rhythmicContrast: 0.21094732405617833
purpose: []
